language: python
env:
  matrix:
    - TARGET=deb
    - TARGET=alpine
  global:
    - DOCKER_REPO=$TRAVIS_REPO_SLUG
    - DOCKERFILE_PATH=Dockerfile-$TARGET
services:
  - docker
install:
  - if [ -z "$TRAVIS_TAG" ]; then echo "Not a tag, exiting" && exit 0; fi
  - make $TARGET
  - |
    echo "$DOCKER_CLOUD_PASSWORD" \
        | docker login -u "$DOCKER_CLOUD_USER" --password-stdin
  - make push$TARGET
