language: python
env:
  matrix:
    - TARGET=deb
    - TARGET=alpine
  global:
    - DOCKER_REPO=$TRAVIS_REPO_SLUG
    - DOCKERFILE_PATH=Dockerfile-$TARGET
services:
  - docker
install:
  - make $TARGET
  - |
    echo "$DOCKER_CLOUD_PASSWORD" \
        | docker login -u "$DOCKER_CLOUD_USER" --password-stdin
  - |
    if [ -z "$TRAVIS_TAG" ]; then
        echo "No tag, not deploying."
    else
        echo "Tag: $TRAVIS_TAG"
        make push$TARGET
    fi
