#------------------------------------------------------------------------------
# CREATE docker-meta.yml
ARG DOCKER_TAG
ARG NAME
ARG VERSION
ARG COMMIT
ARG URL
ARG BRANCH
ARG DATE
ARG REPO
ARG DOCKERFILE_PATH
FROM alpine AS meta
ARG DOCKER_TAG
ARG NAME
ARG VERSION
ARG COMMIT
ARG URL
ARG BRANCH
ARG DATE
ARG REPO
ARG DOCKERFILE_PATH
COPY "${DOCKERFILE_PATH}" /provision/"${DOCKERFILE_PATH}"
RUN echo >>/docker-meta.yml "- name: ${NAME}" \
    && echo >>/docker-meta.yml "  version: ${VERSION}" \
    && echo >>/docker-meta.yml "  commit: ${COMMIT}" \
    && echo >>/docker-meta.yml "  url: ${URL}" \
    && echo >>/docker-meta.yml "  branch: ${BRANCH}" \
    && echo >>/docker-meta.yml "  date: ${DATE}" \
    && echo >>/docker-meta.yml "  repo: ${REPO}" \
    && echo >>/docker-meta.yml "  docker_tag: ${DOCKER_TAG}" \
    && echo >>/docker-meta.yml "  dockerfile_path: ${DOCKERFILE_PATH}" \
    && echo >>/docker-meta.yml "  dockerfile: |" \
    && sed >>/docker-meta.yml 's/^/    /' </provision/"${DOCKERFILE_PATH}" \
    && rm -r /provision
# END CREATE docker-meta.yml
#------------------------------------------------------------------------------

# need glibc installed for proprietary stuff like conda. still a small layer.
FROM frolvlad/alpine-glibc:alpine-3.10

#------------------------------------------------------------------------------
# APPEND docker-meta.yml
COPY --from=meta /docker-meta.yml /new-docker-meta.yml
RUN cat /new-docker-meta.yml >>/docker-meta.yml \
    && echo Full meta: \
    && cat /docker-meta.yml \
    && rm /new-docker-meta.yml
# END APPEND docker-meta.yml
#------------------------------------------------------------------------------

# set up anaconda for user 'llama' and install datagrid
# __curl function taken from:
# https://unix.stackexchange.com/questions/83926/how-to-download-a-file-using-just-bash-and-nothing-else-no-curl-wget-perl-et
RUN adduser --disabled-password --gecos "" llama \
        && apk --no-cache add \
            bash \
            curl \
            bzip2 \
            vim \
            git \
            font-bitstream-type1 \
            graphviz \
            htop \
            ncdu \
            openssh \
        && chown -R llama:llama /home/llama \
        && su llama -c " \
            cd ~ \
                && curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh >~/miniconda.sh \
                && sh ~/miniconda.sh -b -f -p /home/llama/miniconda3 \
                && rm ~/miniconda.sh \
                && /home/llama/miniconda3/bin/conda update conda \
                && /home/llama/miniconda3/bin/conda update --all \
                && /home/llama/miniconda3/bin/conda config --add channels conda-forge \
                && /home/llama/miniconda3/bin/conda init bash \
                && rm -r ~/miniconda3/pkgs \
        "
